### ISSUE TITLE
如果cell能滑动就好了

### ISSUE THREAD

**Issue by chaochaohao** [liufengting/FTPopMenu#1]
如果cell能滑动就好了

**Comment by liufengting** [comment]
目前的逻辑：如果cell过多超过屏幕，才能滑动。cell 太少，不能滑动，这是我在代码里手动设置的。当然如果你想要始终滑动的话修改两行代码就可以了。
- Line 116

```
        _menuTableView.scrollEnabled = NO; 
```

->

```
        _menuTableView.scrollEnabled = YES;
```
- Line 139

```
    _menuTableView.scrollEnabled = shouldAutoScroll;
```

->

```
    _menuTableView.scrollEnabled = YES;
```

只要修改这两行代码就可以了。

**Comment by liufengting** [comment]
sorry。看错项目名了。推荐使用我的另一个：https://github.com/liufengting/FTPopOverMenu

我看了一下这个项目的demo。cell确实是可以滑动的，能否把你的需求描述的详细一点？
